using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using TechJockeys.Data;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));
builder.Services.AddDatabaseDeveloperPageExceptionFilter();

builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = false)
    .AddRoles<IdentityRole>() // authorization (roles / permissions) NOT enabled by default, must manually enable
    .AddEntityFrameworkStores<ApplicationDbContext>();
builder.Services.AddControllersWithViews();

builder.Services.AddAuthentication()
    .AddGoogle(
        options => {
            options.ClientId = builder.Configuration.GetSection("Authentication:Google")["ClientId"] ?? "";
            options.ClientSecret = builder.Configuration.GetSection("Authentication:Google")["ClientSecret"] ?? "";
        }
    );

// Add session services with default configs
builder.Services.AddSession();

// Add swagger/openapi services
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseMigrationsEndPoint();
}
else
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

// Enable swagger middleware in the app object
app.UseSwagger();
app.UseSwaggerUI(c => {
    // Json file path for swagger UI - this is generated by the swagger middleware above
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "TechJockeys API V1");
});


app.UseHttpsRedirection();
app.UseRouting();

app.UseAuthentication(); // enables third-party auth configured above
app.UseAuthorization();
// Enable session middleware in the app object
app.UseSession();

app.MapStaticAssets();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}")
    .WithStaticAssets();

app.MapRazorPages()
   .WithStaticAssets();

app.Run();
